### ISSUE TITLE
Plugin incompatibility: Surbma Divi Lightbox

### ISSUE THREAD

**Issue by s-a-s-k-i-a** [s-a-s-k-i-a/Divi-Lightbox-for-Jetpack-Tiled-Galleries#1]
Surbma Divi Lightbox overrides this plugin's jQuery code, because it applies the .et_pb_lightbox_image css class more globally via ~~php pattern matching within the post/page content.~~ jQuery and adding this class to any anchor that has children img 
I seem to be unable to overwrite this jQuery addClass and do removeClass if a.hasClass ... 
 
@surbma
Maybe we could cowork here, so both plugins can be activated at the same time.

**Comment by Surbma** [comment]
Hi @s-a-s-k-i-a,

thank you for your feedback! Yes, I'm ready to work together to find a solution, that makes both plugin works as expected to users.

My plugin is adding the et_pb_lightbox_image class via javascript, not via php. It follows a simple logic: it adds this class to all links, that has an image as a child.

So please explain me, what is the exclusion, when it is not valid, if somebody wants to use the Divi lightbox. Even I'd like to understand, why somebody wants to activate both plugins.

Is is something, I have to modify in my code, or is it something, that you can apply to your code?

**Comment by s-a-s-k-i-a** [comment]
Hi @Surbma! Thanks for your quick reply!

Ah yes, you use jquery as well! I was in another snippet that does this using php patterns/regex in my head, when I wrote the issue description. Sorry for that!

Ok let me answer the question of why both plugins might be interesting to a user:
your plugin adds the simple lightbox option via magnific popup that is included in Divi.

However there is an "extended" lightbox via magnific popup option especially for gallery images integrated in Divi.
So when you open a jetpack gallery image in Divi's lightbox with my plugin you will also see the navigation arrows and pagination as well as image alt in overlay image's title field. You will be able to navigate through the entire gallery without having to close the overlay and manually click each gallery image to see it in the lightbox as it is the case when only using your plugin.

hope this makes sense ;)

So back to topic:
I am somehow unable to remove the class from the image parent a that your plugin forces on it.. 
do you maybe know why?

You'd have to place an exception to your addClass method if my plugin is active to the following image parent a's in this DOM structure:

**div.tiled-gallery-item a** img

The <code>div.tiled-gallery-item a</code> must not have class .et_pb_lightbox_image for the gallery magnific lightbox to work.

Thanks!

**Comment by Surbma** [comment]
I understand the difference between the two plugins. Can you please provide a working example site, where I can see your plugin with a gallery?

I see, what I can do...

**Comment by s-a-s-k-i-a** [comment]
Sure have a look at this page:
http://lightbox-test.saskialund.de/

**Comment by s-a-s-k-i-a** [comment]
Obsolete since [release v1.0.4](https://github.com/s-a-s-k-i-a/Divi-Lightbox-for-Jetpack-Tiled-Galleries/releases/latest)
This plugin now adds Divi's native lightbox functionality to simple images with media links as well as Jetpack Tiled galleries.

**Comment by Surbma** [comment]
Good idea! I will also integrate Jetpack's Tiled galleries for my plugin.
